### ISSUE TITLE
Proofs of Storage

### ISSUE THREAD

**Issue by dryajov** [status-im/codex-research#16]
Proofs of storage are an integral part of the current Dagger design. They are crucial at providing both security of data as well as an environment capable of sustaining economic incentives.

The topic of proofs of storage has been well researched in academia and in the context of centralized storage providers (Microsoft, Amazon, Google, etc...)

Our objective is to identify a solution that will provide strong data security, persistence and availability guarantees. So far the two most well known approaches are "Provable Data Possession" and "Proofs of Retrievability"; a third solution known as "Proofs of Replication" is also relevant, but so far seems the least suitable for our setup. Nevertheless, we're considering any approach that will yield the expected properties.

**Outstanding Questions**

Determine the best possible schemes in terms of:

- Security - how secure the overall schemes is in a trustless p2p network
- Performance - how fast it performs in a real setting
  - when applied to large files/data sets (GB/TB sizes)
  - when used on fast changing data
    - and under what assumptions
  - in a p2p network conformed by many disparate devices
- Compactness - how large are the proofs both at the storage origin as well as the "public verifier" perspective
    - we need compact proofs for optimal on-the-wire performance
    - we need compact proofs due to potential on chain storage limitations
      - can we aggregate the proofs?
    - we need compact proofs due to cost-of-storage for clients, verifiers, etc...
    - preferably stateless to prevent state management complexity

**Topics of Interest**:

- [x] #17 
- [x] #18 
- [x] #19 
- [ ] #34
- [ ] #35
  - [ ] #71
- [x] #36
  - [x] Bit based aggregation/compression schemes - https://ethresear.ch/t/1-bit-aggregation-friendly-custody-bonds/2236
- [ ] #31
- [x] #30 

**PoC Opportunities**:

- [ ] Pluggable "proofs of storage" framework
- [ ] Bit and Signature aggregation schemes
- [ ] Homomorphic Tags
- [ ] Erasure Coding
- [ ] Authenticated data structures
  - [ ] Verkle tries
  - [ ] Authenticated skip lists

**Acceptance Criteria**:

Identify the correct scheme or a combination of schemes that will satisfy the following properties

- [ ] Help support data durability - i.e. by detecting that the redundancy factor is not being upheld
  - [ ] Confirm that data durability is determined by redundancy
- [ ] Enable efficient and secure auditing of storage providers over time
  - [ ] Define what efficient means
  - [ ] Define what secure means
  - [ ] Define what "over time" means
- [ ] Has the following desirable properties
  - [ ] Efficiently handle arbitrary sized data sets - both small and large
    - small < ~1MB
    - large > ~1TB
  - [ ] Determine which type of data we need and can support 
    - [ ] private vs public
      - [ ] Define what private data means in this context
      - [ ] Define what public data means in this context
    - [ ] static vs dynamic
      - [ ] Define what static data means in this context
      - [ ] Define what dynamic data means in this context
