### ISSUE TITLE
Proofs of Replication

### ISSUE THREAD

**Issue by dryajov** [status-im/codex-research#19]
- [ ] Understand how PoRep is defined and what services and security guarantees it provides.

- [ ] Understand how schemes/protocols providing PoR work.

- [ ] Research literature for variants of PoRep and map differences.

- [ ] Understand how can we use it in dagger and which variant is desired.
